### ISSUE TITLE
Remember/preserve user color.

### ISSUE THREAD

**Issue by Sergio3** [tykeal/ep_ldapauth#19] opened 2015-02-23 08:52 UTC
Hello guys,

Is there a way to remember (or where should I start to achieve) the last user color between sessions? For example if Paul has green color, then Paul always have the green color until he decide to change it.

Thank you and congratulations for all the good job done with this plugin!

**Comment by tykeal** [comment] 2015-02-23 14:42
This is essentially a duplicate of issue #9 . For the record, I have no idea why the color is not preserved. I'm not touching the parts of code that modify color (at least I don't think I am).

**Closed by tykeal** 2015-02-23 14:42 UTC
